server:
  port: 8762
spring:
  application:
    name: microservice-config
  profiles:
    active: dev
  # 配置中心git仓库
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://gitee.com/zhipenghuang/microservice-config-repo.git
          searchPaths:
          username:
          password:

# 将配置中心注册到eureka实现高可用
eureka:
    instance:
        statusPageUrlPath: /actuator/info
        healthCheckUrlPath: /actuator/health
    client:
        serviceUrl:
#            defaultZone: http://localhost:8761/eureka/
                    # docker 部署开启
            defaultZone: http://localhost:8761/eureka/